[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
addopts = "--strict-markers --disable-pytest-warnings"
markers = [
  "training: tests that involve training models"
]

[tool.coverage.run]
omit = [
  private/var/*
  *conftest.py
]